#include "main.h"
#include "app_rtos.h"

UART_HandleTypeDef huart2;
TIM_HandleTypeDef  htim2;

/* Forward declarations if not generated by CubeMX */
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_USART2_UART_Init(void);
void MX_TIM2_Init(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_TIM2_Init();

    MX_FREERTOS_Init();

    vTaskStartScheduler();

    while (1)
    {
        /* Should never reach here if scheduler is running */
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while (1)
    {
        /* Blink LED or trap here */
    }
}
